DATA:
  BATCH_SIZE: 8
  FILTER:
    MAX_DEPTH: 65
    MAX_OCCLUSION: 2
    MAX_TRUNCATION: 0.5
    MIN_DEPTH: 2
    MIN_HEIGHT: 25
  NUM_WORKERS: 4
  ROOT: /home/jimmy/PythonProjects/monocon_na565/kitti_dataset/KITTIDataset
  TEST_SPLIT: val
  TRAIN_SPLIT: train
DESCRIPTION: MonoCon Default Configuration
GPU_ID: 0
MODEL:
  BACKBONE:
    IMAGENET_PRETRAINED: true
    NUM_LAYERS: 34
  HEAD:
    MAX_OBJS: 50
    NUM_CLASSES: 3
OUTPUT_DIR: exps
PERIOD:
  EVAL_PERIOD: 1
  LOG_PERIOD: 50
RESUME_DIR: null
SEED: 543000710
SOLVER:
  CLIP_GRAD:
    ENABLE: true
    MAX_NORM: 35
    NORM_TYPE: 2.0
  OPTIM:
    LR: 0.000225
    NUM_EPOCHS: 200
    WEIGHT_DECAY: 1.0e-05
  SCHEDULER:
    ENABLE: true
USE_BENCHMARK: false
VERSION: v1.0.3

